name: Chore - update version of Alpine linux

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  update-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load .env and export variable
        id: load-env
        run: |
          set -a
          source .env
          set +a
          echo "alpine_version=$ALPINE_VERSION" >> $GITHUB_OUTPUT

      - name: Get latest Alpine version
        id: latest-version
        run: |
          ALPINE_DIGEST="$(curl -s 'https://hub.docker.com/v2/repositories/library/alpine/tags?name=latest' | jq -r '.results[] | select(.name == "latest") | .digest')"
          ALPINE_LATEST_VERSION="$(curl -s 'https://hub.docker.com/v2/repositories/library/alpine/tags?page_size=100' \
          | jq -r '.results[] | select(.digest == "'$ALPINE_DIGEST'") | select(.name | test("^[0-9]+\\.[0-9]+$")) | .name' \
          | head -n 1)"

          : "${ALPINE_LATEST_VERSION:?Error: Unable to fetch current Alpine version}"

          echo "version=${ALPINE_LATEST_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Compare ALPINE_VERSION and ALPINE_LATEST_VERSION
        id: compare
        run: |
          if [ "${{ steps.load-env.outputs.alpine_version }}" = "${{ steps.latest-version.outputs.version }}" ]; then
            echo "Versions match. Exiting."
            exit 0
          else
            echo "New version. Create commit and PR."
            echo "update_alpine=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Update .env
        if: ${{ steps.compare.outputs.update_alpine == 'true' }}
        run: |
          sed -i 's/^ALPINE_VERSION=.*/ALPINE_VERSION=${{ steps.latest-version.outputs.version }}/' .env
          cat .env

      - name: Commit changes
        if: ${{ steps.compare.outputs.update_alpine == 'true' }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "📦 chore(deps): bump Alpine Linux to ${{ steps.latest-version.outputs.version }}"

      - name: Push changes
        if: ${{ steps.compare.outputs.update_alpine == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore/update-alpine-linux-${{ steps.latest-version.outputs.version }}

      - name: Create Pull Request
        if: ${{ steps.compare.outputs.update_alpine == 'true' }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore/update-alpine-linux-${{ steps.latest-version.outputs.version }}
          title: "[GithubAction] Update the Alpine linux version"
          body: |
            Automatically generated by a GitHub Action.

              - Updates the Alpine Linux base image to version `${{ steps.latest-version.outputs.version }}`.
